image: maven:3.5.3-jdk-8

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/
    
maven_build:
  stage: test
  script: 
    - mvn clean
    - mvn surefire-report:report
    - mvn site -DgenerateReports=false
    - mvn jacoco:report
    - sed 's/.*\(Total[^%]*%\).*/\1/' target/site/jacoco/index.html
    - mvn exec:java
  allow_failure: true  
  only:
    - master
  artifacts:
    paths:
      - target/site/

pages:
  stage: deploy
  script:
    - mv target/site public
    - cp public/surefire-report.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master