image: maven:3.5.3-jdk-8

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/
    - target/
    
maven_build:
  stage: test
  script: mvn surefire-report:report
  allow_failure: true  
  artifacts:
    paths:
      - target/site/

pages:
  stage: deploy
  script:
    - mkdir public
    - cp target/site/surefire-report.html public
  artifacts:
    paths:
      - public
  only:
    - master