spring:
  profiles:
    active: prod
  aop:
    proxy-target-class: true

mybatis:
  config-location: classpath:query/mybatis-config.xml

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com:
      honsul: DEBUG
    jdbc:
      sqlonly: OFF 
      audit: OFF
      resultset: OFF
      connection: OFF
      sqltiming: DEBUG
---
# Local Development Configuration 
spring:
  profiles: local

phantomjs:
  binary:
    path: E:/ProjectHome/tools/webdriver/phantomjs.exe
webdriver:
  chrome:
    driver: E:/ProjectHome/tools/webdriver/chromedriver.exe

debug: true
    
---
# Production Configuration 
spring:
  profiles: prod
        
phantomjs:
  binary:
    path: /home/ec2-user/tools/webdriver/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
webdriver:
  chrome:
    driver: E:/ProjectHome/tools/webdriver/chromedriver.exe
    
debug: false

logging:
  level:
    root: INFO
