spring:
  profiles:
    active: local
  aop:
    proxy-target-class: true

mybatis:
  config-location: classpath:query/mybatis-config.xml

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com:
      honsul: DEBUG
    jdbc:
      sqlonly: OFF 
      audit: OFF
      resultset: OFF
      connection: OFF
      sqltiming: DEBUG
    org:
      apache:
        coyote:
          http11: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(%logger{40}.%method){cyan} %clr(:){faint} %m%n"
    
slack:
  channels:
    honsul-holiday: https://hooks.slack.com/services/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

rtmUrl: https://slack.com/api/rtm.start?token=xoxb-5002703614-380571762386-bnDCJQiB31mC2quzycuFGLdn&simple_latest&no_unreads
slackBotToken: xoxb-5002703614-380571762386-bnDCJQiB31mC2quzycuFGLdn
slashCommandToken: <paste your slash command token>
slackIncomingWebhookUrl: https://hooks.slack.com/services/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

---
# Local Development Configuration 
spring:
  profiles: local

phantomjs:
  binary:
    path: E:/ProjectHome/tools/webdriver/phantomjs.exe
webdriver:
  chrome:
    driver: E:/ProjectHome/tools/webdriver/chromedriver.exe

telegram:
  bot-tokens:
    HuegoBot: 520929795:AAHwDezSwwVXMF7NkdfNU2rcW8mQ1-0DC70
        
---
# Production Configuration 
spring:
  profiles: prod
        
phantomjs:
  binary:
    path: /home/ec2-user/tools/webdriver/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
webdriver:
  chrome:
    driver: E:/ProjectHome/tools/webdriver/chromedriver.exe

telegram:
  bot-tokens:
    HuegoBot: 614358181:AAF2jLdgmlH1MDJ8L37v6GOGZg3TBmhFpGo

logging:
  level:
    root: INFO
    com:
      honsul: INFO
    jdbc:
      sqlonly: OFF 
      audit: OFF
      resultset: OFF
      connection: OFF
      sqltiming: INFO
