debug: true

spring:
  aop:
    proxy-target-class: true
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:honsuldb;DB_CLOSE_DELAY=-1
    #driverClassName: net.sf.log4jdbc.DriverSpy
    #url: jdbc:log4jdbc:h2:mem:honsuldb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true

mybatis:
  config-location: classpath:query/mybatis-config.xml

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    com: DEBUG
    log4jdbc: 
      debug: DEBUG
    jdbc:
      sqlonly: OFF 
      audit: OFF
      resultset: OFF
      connection: OFF
      sqltiming: DEBUG
    

