INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R001', '좌구산자연휴양림');
INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R002', '충북알프스자연휴양림');
INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R003', '광치자연휴양림');
INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R004', '문성자연휴양림');
INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R005', '봉황자연휴양림');
INSERT INTO RESORT(RESORT_ID, RESORT_NM) VALUES('R006', '계명산자연휴양림');