INSERT INTO HOTEL(HOTEL_ID, HOTEL_NM) VALUES('H001', '좌구산자연휴양림');
INSERT INTO HOTEL(HOTEL_ID, HOTEL_NM) VALUES('H002', '충북알프스자연휴양림');
INSERT INTO HOTEL(HOTEL_ID, HOTEL_NM) VALUES('H003', '광치자연휴양림');
INSERT INTO HOTEL(HOTEL_ID, HOTEL_NM) VALUES('H004', '문성자연휴양림');
