/* 휴양림 */
CREATE TABLE RESORT (
  RESORT_ID VARCHAR(255) NOT NULL,
  RESORT_NM VARCHAR(255) NOT NULL,
  HOMEPAGE  VARCHAR(255) ,
  PHOTO     VARCHAR(255) ,
  REGION    VARCHAR(255) , 
  ADDRESS   VARCHAR(255) ,
  PHONE     VARCHAR(255) ,  
  INSERT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESORT_ID)
)
COMMENT='휴양림'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

/* 숙소정보 */
DROP TABLE IF EXISTS ROOM;

CREATE TABLE ROOM (
  RESORT_ID VARCHAR(255) NOT NULL,
  ROOM_NM VARCHAR(255) NOT NULL,
  ROOM_TYPE VARCHAR(255) NOT NULL, 
  ROOM_TYPE_NM VARCHAR(255) NOT NULL, 
  OCCUPANCY VARCHAR(255),
  SPACE VARCHAR(255),
  INFO VARCHAR(255),
  PRICE BIGINT DEFAULT 0 NOT NULL,
  PEAK_PRICE BIGINT DEFAULT 0 NOT NULL, 
  INSERT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESORT_ID, ROOM_NM)
)
COMMENT='숙소정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

/* 예약현황 */
DROP TABLE IF EXISTS BOOKING;

CREATE TABLE IF NOT EXISTS BOOKING(
  RESORT_ID VARCHAR(255) NOT NULL,
  BOOKING_DT DATE NOT NULL, 
  ROOM_NM VARCHAR(255) NOT NULL,
  INSERT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESORT_ID, BOOKING_DT, ROOM_NM)
)
COMMENT='예약현황'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

/* 예약현황 방금전*/
DROP TABLE IF EXISTS BOOKING_PREV;

CREATE TABLE IF NOT EXISTS BOOKING_PREV(
  RESORT_ID VARCHAR(255) NOT NULL,
  BOOKING_DT DATE NOT NULL, 
  ROOM_NM VARCHAR(255),
  INSERT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESORT_ID, BOOKING_DT, ROOM_NM)
)
COMMENT='예약현황 방금전'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

/* 구독자 */
DROP TABLE IF EXISTS SUBSCRIBER;

CREATE TABLE SUBSCRIBER (
  SUBSCRIBER_ID VARCHAR(255) NOT NULL,
  SUBSCRIBER_TYPE VARCHAR(255) NOT NULL DEFAULT 'telegram', 
  BOOKING_DT    VARCHAR(8) NOT NULL,
  RESORT_ID     VARCHAR(255) NOT NULL, 
  ROOM_TYPE     VARCHAR(255) NOT NULL,
  USE_YN        VARCHAR(1) NOT NULL DEFAULT 'Y',  
  INSERT_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DT DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (SUBSCRIBER_ID, BOOKING_DT, RESORT_ID, ROOM_TYPE)
)
COMMENT='구독자'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

/* CALENDAR */
CREATE TABLE CALENDAR (
  DT         DATE NOT NULL,
  YEAR       INTEGER NOT NULL,
  MONTH      INTEGER NOT NULL, -- 1 to 12
  DAY        INTEGER NOT NULL, -- 1 to 31
  DAY_NM     VARCHAR(255) NOT NULL, -- 'Monday', 'Tuesday'...
  MONTH_NM   VARCHAR(255) NOT NULL, -- 'January', 'February'...
  HOLIDAY_YN CHAR(1) DEFAULT 'N' CHECK (HOLIDAY_YN in ('Y', 'N')),
  DAYOFF_YN  CHAR(1) DEFAULT 'N' CHECK (DAYOFF_YN in ('Y', 'N')),
  UNIQUE IX_CALENDAR_01 (YEAR, MONTH, DAY),
  PRIMARY KEY (DT)
)
COMMENT='Calendar'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;